swagger: '2.0'
info:
  description: Набор сервисов для работы с системой учета /ООО Ромашка/
  version: "1.0.0"
  title: RestAPI
consumes:
  - application/json
  - application/xml
  - application/text
produces:
  - application/json
  - application/xml
  - application/text
basePath: "/api"

paths:
  /filter/:
    post:
      summary: Изменить значения для фильтрации
      operationId: main.filter
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
      parameters:
        - name: name
          in: query
          description: Значение фильтрации по name
          required: false
          type: string
        - name: id
          in: query
          description: Значение фильтрации по id
          required: false
          type: string

  /reports/formats:
    get:
      summary: Получить список форматов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка

  /reports/ranges/{format}:
    get:
      summary: Получить список единиц измерения
      operationId: main.reportRanges
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/groups/{format}:
    get:
      summary: Получить список групп
      operationId: main.reportGroups
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/nomenclatures/{format}:
    get:
      summary: Получить список номенклатуры
      operationId: main.reportNomenclatures
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/receipts/{format}:
    get:
      summary: Получить список рецептов
      operationId: main.reportReceipts
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer
